// SPDX-License-Identifier: MIT OR Apache-2.0

//! Makes sure the generated Tailwind sheet exists before the crate compiles.
//!
//! `assets/tailwind.css` is a build artifact: `dx` regenerates it from the root
//! `tailwind.css` on every Android build, so it is not tracked by git. But
//! `asset!("/assets/tailwind.css")` resolves at macro-expansion time and fails
//! the build outright when the file is missing — which would break
//! `cargo test --workspace` on a fresh clone, before any `dx` run.
//!
//! So: create an empty sheet if there is none, and never touch an existing one.
//! The styles themselves come from `dx`; this only guarantees the file exists.

use std::path::Path;

fn main() {
    println!("cargo:rerun-if-changed=build.rs");
    // Declared so deleting the sheet later (a `git clean`, a stale checkout)
    // re-runs this script: with only `build.rs` declared, cargo would keep its
    // fingerprint fresh, skip the script, and fail on the missing asset.
    println!("cargo:rerun-if-changed=assets/tailwind.css");

    let sheet = Path::new("assets/tailwind.css");
    if sheet.exists() {
        return;
    }
    if let Some(parent) = sheet.parent() {
        if let Err(e) = std::fs::create_dir_all(parent) {
            println!("cargo:warning=could not create {}: {e}", parent.display());
            return;
        }
    }
    if let Err(e) = std::fs::write(
        sheet,
        "/* Generated by `dx build` from the root tailwind.css. */\n",
    ) {
        println!("cargo:warning=could not create {}: {e}", sheet.display());
    }
}
